const CONFIG = {
    introTitle: 'Hee luu anh Bảo!',
    introDesc: `Em có điều này muốn hỏi , nhớ phải trả lời thật lòng nha`,
    btnIntro: 'oke',
    title: 'Anh yêu em rồi có phải không 😙',
    desc: 'Anh không trả lời hoặc thoát ra, tức là cậu là ck em đó nha :> ',
    btnYes: 'Đương nhiên là yêu <33',
    btnNo: 'em mơ à :333',
    question:'Nói cho em lý do vì sao anh yêu em đii <3',
    btnReply: 'Gửi cho em <3',
    reply: 'Yêu không cần lý do <33333333',
    mess: 'Em biết mà 🥰. Love you 300.000 😘😘',
    messDesc: 'còn giờ thì chờ gì nữa mà không inbox cho em tiếp đi .',
    btnAccept: 'Okiiiii lun <3',
   
